import { StrictMode, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import type { PresenceState } from "../contracts/index.js";
import {
  queryPresentationJobs,
  type PresentationJobQuery,
  type PresentationJobResult,
  type PresentationSort,
  type SortDirection,
} from "../masking/query.js";
import type { OperationsPresentationDto, PresentationField } from "../masking/presentation.js";
import type { OperationsApiResponse } from "../server/operations-api.js";
import "./styles.css";

const labels: Readonly<Record<string, string>> = {
  BLANK: "Blank in source", EXPLICIT_NA: "NA in source", COLUMN_UNAVAILABLE: "Not collected in this period",
  SOURCE_ANNOTATION: "Source annotation", CROSS_PERIOD_ANNOTATION: "Attributed elsewhere in source",
  MALFORMED: "Could not parse", FORMULA: "Formula result (source)", FORMULA_ERROR: "Source formula error",
};
const metricFields = ["burn_sheets", "liner_sheets", "liner_area", "liner_size", "coil_pc_count", "coil_lbs", "optimized_pc_count", "optimized_lbs"] as const;
const months = ["Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"] as const;
const presenceOptions: readonly PresenceState[] = ["VALUE", "BLANK", "EXPLICIT_NA", "COLUMN_UNAVAILABLE", "SOURCE_ANNOTATION", "CROSS_PERIOD_ANNOTATION", "MALFORMED", "FORMULA", "FORMULA_ERROR"];
const initialParam = (name: string, fallback = "ALL"): string => new URLSearchParams(location.search).get(name) ?? fallback;

export function Value({ field }: { field: PresentationField }) {
  return field.presence === "VALUE" ? <span>{String(field.display ?? "")}</span> : <span className={`presence presence-${field.presence.toLowerCase()}`}>{labels[field.presence] ?? field.presence}</span>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="detail-section"><h3>{title}</h3><div className="detail-grid">{children}</div></section>; }
function Datum({ label, field }: { label: string; field: PresentationField }) {
  const hasNormalized = field.normalizedDisplay !== null && field.normalizedDisplay !== undefined;
  return <div className="datum"><span>{label}{hasNormalized && <i className="normalized-mark">Normalized</i>}</span><strong>{hasNormalized ? String(field.normalizedDisplay) : <Value field={field} />}</strong>{hasNormalized && String(field.display ?? "") !== String(field.normalizedDisplay) && <small>Raw: {String(field.display ?? labels[field.presence] ?? "")}</small>}</div>;
}

function JobDetail({ job, onBack, onSource }: { job: OperationsPresentationDto; onBack: () => void; onSource: () => void }) {
  return <div className="detail-page"><button className="back-link" onClick={onBack}>← Back to Jobs / Releases</button><header className="detail-hero"><div><span className="eyebrow">JOB / RELEASE · {job.provenance.sheetName} ROW {job.provenance.rowNumber}</span><h1><Value field={job.jobName} /></h1><p><Value field={job.customer} /> · <Value field={job.po} /></p></div><div className="grouping-badge"><span>PROJECT / PO GROUPING</span><strong>Provisional</strong><small>Awaiting Titan definition</small></div></header>
    <Section title="Identity"><Datum label="Legacy Job #" field={job.legacyJobNumber} /><Datum label="Customer" field={job.customer} /><Datum label="PO" field={job.po} /><Datum label="Job name / release" field={job.jobName} /></Section>
    <Section title="Schedule"><Datum label="Due day" field={job.dueDay} /><Datum label="Due date" field={job.dueDate} /><Datum label="Due time" field={job.dueTime} /><Datum label="Priority" field={job.priority} /></Section>
    <Section title="Production"><Datum label="Raw recorded status" field={job.status} /><Datum label="Exposed" field={job.exposed} />{Object.entries(job.metrics).map(([name, metric]) => <Datum key={name} label={name.replaceAll("_", " ")} field={metric} />)}</Section>
    <Section title="Buyout"><Datum label="Ordered" field={job.buyoutOrdered} /><Datum label="Vendor & PO source (composite)" field={job.vendorPoComposite} /><Datum label="Received" field={job.buyoutReceived} /></Section>
    <Section title="Delivery"><Datum label="Delivery / Will Call" field={job.deliveryMode} /><Datum label="Day / date" field={job.deliveryDayDate} /><Datum label="Time" field={job.deliveryTime} /><Datum label="Contact" field={job.deliveryContact} /><Datum label="Phone" field={job.phone} /><Datum label="Text source field" field={job.textFlag} /></Section>
    <section className="detail-section"><h3>Office events <span className="prop-label">Independent evidence · no required sequence</span></h3><div className="event-line">{Object.entries(job.officeEvents).map(([name, field]) => <div className="event-card" key={name}><span>{name}</span><strong><Value field={field} /></strong></div>)}</div></section>
    <Section title="Notes"><Datum label="Operational note" field={job.operationalNote} /><Datum label="Office-only note" field={job.officeOnlyNote} /><Datum label="Entered by" field={job.enteredBy} /></Section>
    <section className="detail-section"><h3>Systems Awareness <span className="prop-label">PROP · review mode</span></h3>{job.findings.length ? <div className="finding-list">{job.findings.map((finding) => <article key={finding.evaluationId}><b>{finding.ruleId} · {finding.ruleVersion}</b><p>{finding.reason}</p><small>{finding.sourceCellIds.length} source inputs · proposed review only · exclusions: {finding.exclusions.length ? finding.exclusions.join(", ") : "none"}</small></article>)}</div> : <div className="empty-inline">No proposed review-mode findings for this record. Blocked rules remain excluded.</div>}</section>
    <section className="detail-section provenance-summary"><h3>Provenance</h3><p>{job.provenance.sourceFile} → {job.provenance.sheetName} → row {job.provenance.rowNumber}</p><code>{job.provenance.sourceHash.slice(0, 16)}… · {job.provenance.importBatchId}</code><button onClick={onSource}>Inspect mapped source cells</button></section>
  </div>;
}

function SourceDrawer({ job, close }: { job: OperationsPresentationDto; close: () => void }) {
  const dialogRef = useRef<HTMLElement>(null); const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { const opener = document.activeElement instanceof HTMLElement ? document.activeElement : null; closeRef.current?.focus(); return () => opener?.focus(); }, []);
  const onKeyDown = (event: React.KeyboardEvent<HTMLElement>) => {
    if (event.key === "Escape") { event.preventDefault(); close(); return; }
    if (event.key !== "Tab") return;
    const focusable = [...(dialogRef.current?.querySelectorAll<HTMLElement>("button, [href], input, select, textarea, [tabindex]:not([tabindex='-1'])") ?? [])].filter((element) => !element.hasAttribute("disabled"));
    if (!focusable.length) return; const first = focusable[0]!; const last = focusable[focusable.length - 1]!;
    if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
    if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
  };
  return <div className="drawer-backdrop" onMouseDown={close}><aside ref={dialogRef} className="quick-drawer source-drawer" role="dialog" aria-modal="true" aria-label="Provenance and source cells" onKeyDown={onKeyDown} onMouseDown={(event) => event.stopPropagation()}><button ref={closeRef} className="close" onClick={close} aria-label="Close provenance">×</button><span className="eyebrow">IMMUTABLE SOURCE EVIDENCE</span><h2>{job.provenance.sheetName} · row {job.provenance.rowNumber}</h2><p>{job.provenance.sourceFile}</p><div className="source-list">{job.provenance.fields.map((field) => <article key={field.sourceCellId}><div><b>{field.canonicalField}</b><code>{field.address}</code></div><small>{field.header ?? "No header"} · {field.excelType} · {field.presence}</small><p>{field.rawDisplay ?? labels[field.presence] ?? "No source display"}</p>{field.formulaText && <code>{field.formulaText}</code>}</article>)}</div></aside></div>;
}

interface JobTableProps { results: readonly PresentationJobResult[]; open: (job: OperationsPresentationDto) => void; source: (job: OperationsPresentationDto) => void; selectedIds: ReadonlySet<string>; toggleSelected: (job: OperationsPresentationDto) => void; }
function JobTable({ results, open, source, selectedIds, toggleSelected }: JobTableProps) {
  const onRowKeyDown = (event: React.KeyboardEvent<HTMLTableRowElement>, job: OperationsPresentationDto) => {
    if (event.key === "Enter") { event.preventDefault(); open(job); return; }
    if (event.key === " ") { event.preventDefault(); toggleSelected(job); return; }
    if (event.key.toLowerCase() === "r") { event.preventDefault(); source(job); return; }
    if (event.key !== "ArrowDown" && event.key !== "ArrowUp") return;
    event.preventDefault(); const rows = [...(event.currentTarget.parentElement?.querySelectorAll<HTMLTableRowElement>("tr[data-job-row]") ?? [])]; const current = rows.indexOf(event.currentTarget); rows[current + (event.key === "ArrowDown" ? 1 : -1)]?.focus();
  };
  return <div className="table-frame" role="region" aria-label="Jobs and releases table"><table aria-label="Qualified Jobs and Releases"><thead><tr><th>Attention / select</th><th>Legacy Job #</th><th>Customer</th><th>PO</th><th>Job Name / Release</th><th>Due</th><th>Priority</th><th>Status</th><th>Buyout</th><th>Delivery</th><th>Coil LBS</th><th>Optimized LBS</th><th>Liner Area</th><th>Source</th></tr></thead><tbody>{results.map(({ job, matchLane }) => { const selected = selectedIds.has(job.jobReleaseId); return <tr data-job-row key={job.jobReleaseId} tabIndex={0} aria-selected={selected} className={selected ? "selected-row" : ""} onDoubleClick={() => open(job)} onKeyDown={(event) => onRowKeyDown(event, job)}><td><button className="selection-button" aria-label={`${selected ? "Deselect" : "Select"} ${String(job.jobName.display ?? "record")}`} aria-pressed={selected} onClick={() => toggleSelected(job)}>{selected ? "●" : "○"}</button>{job.findings.length ? <span className="attention">{job.findings.length} PROP</span> : <span className="quiet">—</span>}{matchLane && <span className="match-lane">{matchLane === "SOURCE" ? "Source match" : "Normalized match"}</span>}</td><td><button className="record-link" onClick={() => open(job)}><Value field={job.legacyJobNumber} /></button></td><td><Value field={job.customer} /></td><td><Value field={job.po} /></td><td><Value field={job.jobName} /></td><td><Value field={job.dueDate} /></td><td><Value field={job.priority} /></td><td><span className="status-chip"><Value field={job.status} /></span></td><td><Value field={job.buyoutOrdered} /></td><td><Value field={job.deliveryMode} /></td><td className="metric"><Value field={job.metrics.coil_lbs!} /></td><td className="metric"><Value field={job.metrics.optimized_lbs!} /></td><td className="metric"><Value field={job.metrics.liner_area!} /></td><td><button className="source-button" onClick={() => source(job)}>{job.provenance.sheetName} · {job.provenance.rowNumber}</button></td></tr>; })}</tbody></table>{!results.length && <div className="loading-grid">No records match the current filters.</div>}</div>;
}

const comparisonFields: readonly { key: string; field: (job: OperationsPresentationDto) => PresentationField }[] = [
  { key: "customer", field: (job) => job.customer }, { key: "po", field: (job) => job.po }, { key: "job_name", field: (job) => job.jobName },
  { key: "production_status", field: (job) => job.status }, { key: "priority", field: (job) => job.priority },
  { key: "buyout_ordered", field: (job) => job.buyoutOrdered }, { key: "delivery_mode", field: (job) => job.deliveryMode },
  { key: "coil_lbs", field: (job) => job.metrics.coil_lbs! }, { key: "optimized_lbs", field: (job) => job.metrics.optimized_lbs! },
];
function ComparisonPanel({ jobs, remove }: { jobs: readonly OperationsPresentationDto[]; remove: (id: string) => void }) {
  if (jobs.length < 2) return <div className="history-note"><b>Compare 2–8 source records</b><span>Select rows with Space or the row selection control. Canonical fields align without computing conclusions.</span></div>;
  return <section className="comparison-panel" aria-label="Historical record comparison"><header><div><span className="eyebrow">CANONICAL FIELD ALIGNMENT</span><h2>Compare {jobs.length} source records</h2></div><small>Presence states remain literal. No financial or official production conclusion is computed.</small></header><div className="comparison-scroll"><table><thead><tr><th>Canonical field</th>{jobs.map((job) => <th key={job.jobReleaseId}>{job.provenance.sheetName} · {job.provenance.rowNumber}<button onClick={() => remove(job.jobReleaseId)} aria-label={`Remove ${job.provenance.sheetName} row ${job.provenance.rowNumber} from comparison`}>×</button></th>)}</tr></thead><tbody>{comparisonFields.map((field) => <tr key={field.key}><th>{field.key}</th>{jobs.map((job) => <td key={job.jobReleaseId}><Value field={field.field(job)} /></td>)}</tr>)}</tbody></table></div></section>;
}

interface FilterProps {
  data: OperationsApiResponse; search: string; setSearch: (v: string) => void; status: string; setStatus: (v: string) => void; buyout: string; setBuyout: (v: string) => void;
  delivery: string; setDelivery: (v: string) => void; metricField: string; setMetricField: (v: string) => void; metricPresence: string; setMetricPresence: (v: string) => void;
  metricMin: string; setMetricMin: (v: string) => void; metricMax: string; setMetricMax: (v: string) => void; rule: string; setRule: (v: string) => void;
  sort: PresentationSort; setSort: (v: PresentationSort) => void; direction: SortDirection; setDirection: (v: SortDirection) => void;
  searchRef: React.RefObject<HTMLInputElement | null>; filterRef: React.RefObject<HTMLSelectElement | null>; resultCount: number;
}
function FilterControls(p: FilterProps) {
  const statuses = Object.keys(p.data.summary.statusDistribution).sort();
  return <section className="filter-bar filter-grid" aria-label="Jobs query controls"><label><span>Search records · /</span><input ref={p.searchRef} value={p.search} onChange={(e) => p.setSearch(e.target.value)} placeholder="Customer, PO, job, release…" /></label><label><span>Raw status · f</span><select ref={p.filterRef} value={p.status} onChange={(e) => p.setStatus(e.target.value)}><option value="ALL">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label><span>Buyout source state</span><select value={p.buyout} onChange={(e) => p.setBuyout(e.target.value)}><option value="ALL">All buyout states</option>{p.data.summary.buyoutDistribution.map((item) => <option key={item.key} value={item.key}>{item.label} ({item.count})</option>)}</select></label><label><span>Delivery / Will Call source</span><select value={p.delivery} onChange={(e) => p.setDelivery(e.target.value)}><option value="ALL">All delivery states</option>{p.data.summary.deliveryDistribution.map((item) => <option key={item.key} value={item.key}>{item.label} ({item.count})</option>)}</select></label><label><span>Metric</span><select value={p.metricField} onChange={(e) => p.setMetricField(e.target.value)}><option value="ANY">Any metric</option>{metricFields.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label><label><span>Metric presence</span><select value={p.metricPresence} onChange={(e) => p.setMetricPresence(e.target.value)}><option value="ALL">All presence states</option><option value="NON_VALUE">Any non-value state</option>{presenceOptions.map((item) => <option key={item} value={item}>{labels[item] ?? item}</option>)}</select></label><label><span>Metric minimum</span><input type="number" value={p.metricMin} onChange={(e) => p.setMetricMin(e.target.value)} /></label><label><span>Metric maximum</span><input type="number" value={p.metricMax} onChange={(e) => p.setMetricMax(e.target.value)} /></label><label><span>Finding</span><select value={p.rule} onChange={(e) => p.setRule(e.target.value)}><option value="ALL">All finding states</option>{p.data.rules.map((item) => <option key={item.ruleId} value={item.ruleId}>{item.ruleId} · {item.disposition === "BLOCKED" ? "BLOCKED" : "PROP"}</option>)}</select></label><label><span>Sort</span><select value={p.sort} onChange={(e) => p.setSort(e.target.value as PresentationSort)}><option value="source">Source order</option><option value="customer">Customer</option><option value="jobName">Job name</option><option value="status">Raw status</option><option value="metric">Selected metric</option></select></label><label><span>Direction</span><select value={p.direction} onChange={(e) => p.setDirection(e.target.value as SortDirection)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><div className="filter-result"><strong>{p.resultCount.toLocaleString()}</strong><span>qualified matches</span></div></section>;
}

export function App() {
  const [mode, setMode] = useState<"internal" | "masked">(initialParam("mode", "internal") === "masked" ? "masked" : "internal");
  const [path, setPath] = useState(location.pathname); const [data, setData] = useState<OperationsApiResponse | null>(null); const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState(initialParam("search", "")); const [status, setStatus] = useState(initialParam("status")); const [era, setEra] = useState(initialParam("era")); const [rule, setRule] = useState(initialParam("rule"));
  const [buyout, setBuyout] = useState(initialParam("buyout")); const [delivery, setDelivery] = useState(initialParam("delivery")); const [metricField, setMetricField] = useState(initialParam("metricField", "ANY")); const [metricPresence, setMetricPresence] = useState(initialParam("metricPresence"));
  const [metricMin, setMetricMin] = useState(initialParam("metricMin", "")); const [metricMax, setMetricMax] = useState(initialParam("metricMax", "")); const [sort, setSort] = useState<PresentationSort>(initialParam("sort", "source") as PresentationSort); const [direction, setDirection] = useState<SortDirection>(initialParam("direction", "asc") as SortDirection);
  const [selectedIds, setSelectedIds] = useState<ReadonlySet<string>>(() => new Set(initialParam("compare", "").split(",").filter(Boolean).slice(0, 8))); const [selectionMessage, setSelectionMessage] = useState(""); const [sourceJob, setSourceJob] = useState<OperationsPresentationDto | null>(null);
  const searchRef = useRef<HTMLInputElement>(null); const filterRef = useRef<HTMLSelectElement>(null);

  useEffect(() => { setError(null); setData(null); fetch(`/api/operations?mode=${mode}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json() as OperationsApiResponse & { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Local source service unavailable"); setData(payload); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Local source service unavailable")); }, [mode]);
  useEffect(() => { const pop = () => setPath(location.pathname); addEventListener("popstate", pop); return () => removeEventListener("popstate", pop); }, []);
  useEffect(() => { const keys = (event: KeyboardEvent) => { if (event.key === "/" && document.activeElement?.tagName !== "INPUT") { event.preventDefault(); searchRef.current?.focus(); } if (event.key.toLowerCase() === "f" && !["INPUT", "SELECT", "TEXTAREA"].includes(document.activeElement?.tagName ?? "")) filterRef.current?.focus(); }; addEventListener("keydown", keys); return () => removeEventListener("keydown", keys); }, []);
  useEffect(() => { const url = new URL(location.href); const values: Record<string, string> = { search, status, era, rule, buyout, delivery, metricField, metricPresence, metricMin, metricMax, sort, direction, compare: [...selectedIds].join(",") }; for (const [key, value] of Object.entries(values)) { const defaultValue = key === "metricField" ? "ANY" : key === "sort" ? "source" : key === "direction" ? "asc" : "ALL"; if (!value || value === defaultValue) url.searchParams.delete(key); else url.searchParams.set(key, value); } url.searchParams.set("mode", mode); history.replaceState({}, "", url); }, [search, status, era, rule, buyout, delivery, metricField, metricPresence, metricMin, metricMax, sort, direction, selectedIds, mode]);

  const query: PresentationJobQuery = { search, status, era, buyout, delivery, metricField, metricPresence, metricMin: metricMin === "" ? null : Number(metricMin), metricMax: metricMax === "" ? null : Number(metricMax), findingRuleId: rule, sort, direction };
  const results = useMemo(() => queryPresentationJobs(data?.jobs ?? [], query), [data, search, status, era, buyout, delivery, metricField, metricPresence, metricMin, metricMax, rule, sort, direction]);
  const detailId = path.startsWith("/operations/jobs/") ? decodeURIComponent(path.slice("/operations/jobs/".length)) : null; const detailJob = detailId ? data?.jobs.find((job) => job.jobReleaseId === detailId) ?? null : null;
  const active = path.includes("awareness") ? "awareness" : path.includes("history") ? "history" : path.includes("overview") || path === "/" ? "overview" : path.includes("estimating") ? "estimating" : "jobs";
  const findings = (data?.jobs ?? []).flatMap((job) => job.findings.map((finding) => ({ job, finding }))).filter(({ finding }) => rule === "ALL" || finding.ruleId === rule); const comparedJobs = (data?.jobs ?? []).filter((job) => selectedIds.has(job.jobReleaseId)).slice(0, 8);
  const params = (): Record<string, string> => ({ search, status, era, rule, buyout, delivery, metricField, metricPresence, metricMin, metricMax, sort, direction, compare: [...selectedIds].join(",") });
  const applyOverrides = (o: Record<string, string>) => { if (o.search !== undefined) setSearch(o.search); if (o.status !== undefined) setStatus(o.status); if (o.era !== undefined) setEra(o.era); if (o.rule !== undefined) setRule(o.rule); if (o.buyout !== undefined) setBuyout(o.buyout); if (o.delivery !== undefined) setDelivery(o.delivery); if (o.metricField !== undefined) setMetricField(o.metricField); if (o.metricPresence !== undefined) setMetricPresence(o.metricPresence); };
  const navigate = (nextPath: string, overrides: Record<string, string> = {}) => { applyOverrides(overrides); const url = new URL(nextPath, location.origin); url.searchParams.set("mode", mode); for (const [key, value] of Object.entries({ ...params(), ...overrides })) if (value && !["ALL", "ANY", "source", "asc"].includes(value)) url.searchParams.set(key, value); history.pushState({}, "", url); setPath(url.pathname); };
  const toggleSelected = (job: OperationsPresentationDto) => setSelectedIds((current) => { const next = new Set(current); if (next.has(job.jobReleaseId)) { next.delete(job.jobReleaseId); setSelectionMessage(""); return next; } if (next.size >= 8) { setSelectionMessage("Compare is limited to 8 source records."); return current; } next.add(job.jobReleaseId); setSelectionMessage(""); return next; });
  const removeSelected = (id: string) => setSelectedIds((current) => { const next = new Set(current); next.delete(id); return next; }); const openJob = (job: OperationsPresentationDto) => navigate(`/operations/jobs/${encodeURIComponent(job.jobReleaseId)}`);

  return <div className="app-shell"><aside className="nav-rail"><div className="brand"><span className="brand-mark">T</span><div><strong>TITAN</strong><small>OPERATIONS · RC0</small></div></div><nav aria-label="Primary navigation"><a className={active === "overview" ? "active" : ""} onClick={(e) => { e.preventDefault(); navigate("/operations/overview"); }} href="/operations/overview">Overview</a><a className={active === "jobs" ? "active" : ""} onClick={(e) => { e.preventDefault(); navigate("/operations/jobs"); }} href="/operations/jobs">Jobs / Releases</a><a className={active === "awareness" ? "active" : ""} onClick={(e) => { e.preventDefault(); navigate("/operations/awareness"); }} href="/operations/awareness">Systems Awareness</a><a className={active === "history" ? "active" : ""} onClick={(e) => { e.preventDefault(); navigate("/operations/history"); }} href="/operations/history">Historical Explorer</a><hr /><a className={active === "estimating" ? "active" : ""} onClick={(e) => { e.preventDefault(); navigate("/estimating"); }} href="/estimating">Estimating <small>Sibling</small></a></nav><div className="boundary-note"><strong>Read-only source</strong><span>No workbook writeback</span></div></aside><main>{mode === "masked" && <div className="masked-banner" role="status">MASKED DEMO — NOT SOURCE DATA</div>}<header className="topbar"><div><span className="eyebrow">2025 WORK LEDGER</span><strong>{data ? `${data.snapshot.jobCount.toLocaleString()} qualified records · ${data.snapshot.reviewCount} review rows` : "Loading immutable snapshot…"}</strong></div><div className="topbar-meta"><span>{data?.snapshot.snapshotId ?? "Snapshot pending"}</span><button className="mode-switch" onClick={() => { if (mode === "internal" && !confirm("Use masked presentation for this session?")) return; setMode(mode === "internal" ? "masked" : "internal"); }}>{mode === "internal" ? "Internal Data" : "Masked Demo"}<b>↔</b></button></div></header>
    {error && <div className="error-panel" role="alert"><strong>Source unavailable</strong><span>{error}</span></div>}{!error && !data && <div className="loading-grid">Registering and importing the authorized workbook through the read-only source boundary…</div>}
    {data && detailJob && <JobDetail job={detailJob} onBack={() => navigate("/operations/jobs")} onSource={() => setSourceJob(detailJob)} />}
    {data && !detailJob && active === "jobs" && <><header className="page-head"><div><span className="eyebrow">SOURCE-AWARE RECORDS</span><h1>Jobs / Releases</h1><p>One qualified workbook row per record. Unknowns stay visible.</p></div><div className="source-stamp"><span>SOURCE INTEGRITY</span><strong>Verified unchanged</strong><small>{data.snapshot.fileName}</small></div></header><FilterControls data={data} search={search} setSearch={setSearch} status={status} setStatus={setStatus} buyout={buyout} setBuyout={setBuyout} delivery={delivery} setDelivery={setDelivery} metricField={metricField} setMetricField={setMetricField} metricPresence={metricPresence} setMetricPresence={setMetricPresence} metricMin={metricMin} setMetricMin={setMetricMin} metricMax={metricMax} setMetricMax={setMetricMax} rule={rule} setRule={setRule} sort={sort} setSort={setSort} direction={direction} setDirection={setDirection} searchRef={searchRef} filterRef={filterRef} resultCount={results.length} />{selectionMessage && <p className="selection-message" role="status">{selectionMessage}</p>}<JobTable results={results.slice(0, 500)} open={openJob} source={setSourceJob} selectedIds={selectedIds} toggleSelected={toggleSelected} /></>}
    {data && active === "overview" && <div className="content-page"><header className="page-head"><div><span className="eyebrow">SOURCE-QUALIFIED SYNTHESIS</span><h1>Operations Overview</h1><p>Navigation over qualified records—not an official KPI engine.</p></div></header><section className="snapshot-panel"><div><span>Active source</span><strong>{data.snapshot.fileName}</strong><small>{data.snapshot.sourceHash.slice(0, 20)}…</small></div><div><span>Qualified jobs / releases</span><strong>{data.snapshot.jobCount.toLocaleString()}</strong><small>Deterministic row contract v0.1</small></div><div><span>Review ledger</span><strong>{data.snapshot.reviewCount}</strong><small>Never silently promoted</small></div></section><h2 className="section-title">Proposed review attention</h2><section className="overview-grid">{["OPS-AWR-002", "OPS-AWR-003", "OPS-AWR-004", "OPS-AWR-007"].map((id) => <button key={id} onClick={() => navigate("/operations/awareness", { rule: id })}><span>{id} · PROP</span><strong>{data.summary.findingsByRule[id] ?? 0}</strong><small>Review-mode findings</small></button>)}</section><h2 className="section-title">Dependencies and delivery · source conditions</h2><div className="overview-context"><section><h3>Buyout source state</h3>{data.summary.buyoutDistribution.map((item) => <button key={item.key} onClick={() => navigate("/operations/jobs", { buyout: item.key })}><span>{item.label}</span><b>{item.count}</b></button>)}</section><section><h3>Delivery / Will Call distribution</h3>{data.summary.deliveryDistribution.map((item) => <button key={item.key} onClick={() => navigate("/operations/jobs", { delivery: item.key })}><span>{item.label}</span><b>{item.count}</b></button>)}</section><section><h3>Data quality · metric presence</h3><button onClick={() => navigate("/operations/jobs", { metricField: "ANY", metricPresence: "NON_VALUE" })}><span>Non-value metric cells</span><b>{data.summary.presenceReviewCount.toLocaleString()}</b><small>{data.summary.jobsWithMetricReviewCount.toLocaleString()} records contain review-state metrics</small></button>{data.summary.metricPresenceDistribution.filter((item) => item.key !== "VALUE").slice(0, 5).map((item) => <button key={item.key} onClick={() => navigate("/operations/jobs", { metricField: "ANY", metricPresence: item.key })}><span>{item.label}</span><b>{item.count}</b></button>)}</section></div><h2 className="section-title">Raw production status distribution</h2><section className="distribution">{Object.entries(data.summary.statusDistribution).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([name, count]) => <button key={name} onClick={() => navigate("/operations/jobs", { status: name })}><span>{name}</span><b>{count}</b></button>)}</section><div className="unavailable-callout"><b>Overdue / official annual totals unavailable</b><span>Blocked status/EOD semantics and unreconciled source-summary inclusion policy. No value is shown as zero.</span></div></div>}
    {data && active === "awareness" && <div className="content-page"><header className="page-head"><div><span className="eyebrow">DETERMINISTIC · INSPECTABLE · NON-MUTATING</span><h1>Systems Awareness</h1><p>Only proposed review-mode rules generate findings. Blocked definitions remain browsable and excluded.</p></div></header><section className="filter-bar"><label><span>Rule</span><select value={rule} onChange={(e) => setRule(e.target.value)}><option value="ALL">All proposed findings</option>{data.rules.map((item) => <option key={item.ruleId} value={item.ruleId}>{item.ruleId}</option>)}</select></label><div className="filter-result"><strong>{findings.length}</strong><span>PROP findings</span></div></section><div className="awareness-layout"><section className="finding-table">{findings.slice(0, 500).map(({ job, finding }) => { const sourceFields = job.provenance.fields.filter((field) => finding.sourceCellIds.some((id) => String(id) === field.sourceCellId)); return <article key={finding.evaluationId}><span className="prop-label">PROP · REVIEW</span><button onClick={() => openJob(job)}><Value field={job.jobName} /></button><b>{finding.ruleId} · {finding.ruleVersion}</b><p>{finding.reason}</p><small>{job.provenance.sheetName} row {job.provenance.rowNumber} · inputs {sourceFields.map((field) => field.address).join(", ") || finding.sourceCellIds.length}</small><button className="source-button" onClick={() => setSourceJob(job)}>Inspect finding source</button></article>; })}</section><aside className="rule-catalog"><h3>Rule catalog</h3>{data.rules.map((item) => <div key={item.ruleId}><b>{item.ruleId}</b><span>{item.disposition === "BLOCKED" ? "BLOCKED" : "PROP / REVIEW MODE"}</span><small>{item.title}</small></div>)}</aside></div></div>}
    {data && active === "history" && <div className="content-page"><header className="page-head"><div><span className="eyebrow">AUTHORIZED WORKBOOK EVIDENCE</span><h1>Historical Explorer</h1><p>Compare periods without erasing schema-era missingness.</p></div></header><section className="filter-bar"><label><span>Source month</span><select value={era} onChange={(e) => setEra(e.target.value)}><option value="ALL">All 2025 months</option>{months.map((item) => <option key={item}>{item}</option>)}</select></label><div className="filter-result"><strong>{results.length.toLocaleString()}</strong><span>source records</span></div></section><div className="history-note"><b>Presence states remain literal</b><span>“Not collected in this period” is distinct from “Blank in source,” NA, annotations, malformed values, and numeric 0.</span></div><ComparisonPanel jobs={comparedJobs} remove={removeSelected} />{selectionMessage && <p className="selection-message" role="status">{selectionMessage}</p>}<JobTable results={results.slice(0, 300)} open={openJob} source={setSourceJob} selectedIds={selectedIds} toggleSelected={toggleSelected} /></div>}
    {data && active === "estimating" && <div className="content-page sibling-page"><span className="eyebrow">ISOLATED SIBLING ROUTE</span><h1>Estimating</h1><p>Estimating is intentionally separated from Titan Operations RC0. No Operations state, Quote semantics, pricing logic, or quote-to-job automation crosses this boundary.</p><button onClick={() => navigate("/operations/overview")}>Return to Operations Overview</button></div>}
    {sourceJob && <SourceDrawer job={sourceJob} close={() => setSourceJob(null)} />}</main></div>;
}

const rootElement = document.getElementById("root");
if (rootElement) createRoot(rootElement).render(<StrictMode><App /></StrictMode>);
