import { StrictMode, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import type { OperationsApiResponse } from "../server/operations-api.js";
import type { OperationsPresentationDto, PresentationField } from "../masking/index.js";
import "./styles.css";

const labels: Record<string, string> = { BLANK: "Blank in source", EXPLICIT_NA: "NA in source", COLUMN_UNAVAILABLE: "Not collected in this period", SOURCE_ANNOTATION: "Source annotation", CROSS_PERIOD_ANNOTATION: "Attributed elsewhere in source", MALFORMED: "Could not parse", FORMULA: "Formula result (source)", FORMULA_ERROR: "Source formula error" };
export function Value({ field }: { field: PresentationField }) { return field.presence === "VALUE" ? <span>{String(field.display ?? "")}</span> : <span className={`presence presence-${field.presence.toLowerCase()}`}>{labels[field.presence] ?? field.presence}</span>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="detail-section"><h3>{title}</h3><div className="detail-grid">{children}</div></section>; }
function Datum({ label, field }: { label: string; field: PresentationField }) { return <div className="datum"><span>{label}{"normalizedDisplay" in field && <i className="normalized-mark">Normalized</i>}</span><strong>{"normalizedDisplay" in field && field.normalizedDisplay !== null ? String(field.normalizedDisplay) : <Value field={field} />}</strong></div>; }

function JobDetail({ job, onBack, onSource }: { job: OperationsPresentationDto; onBack: () => void; onSource: () => void }) {
  return <div className="detail-page"><button className="back-link" onClick={onBack}>← Back to Jobs / Releases</button><header className="detail-hero"><div><span className="eyebrow">JOB / RELEASE · {job.provenance.sheetName} ROW {job.provenance.rowNumber}</span><h1><Value field={job.jobName} /></h1><p><Value field={job.customer} /> · <Value field={job.po} /></p></div><div className="grouping-badge"><span>PROJECT / PO GROUPING</span><strong>Provisional</strong><small>Awaiting Titan definition</small></div></header>
    <Section title="Identity"><Datum label="Legacy Job #" field={job.legacyJobNumber} /><Datum label="Customer" field={job.customer} /><Datum label="PO" field={job.po} /><Datum label="Job name / release" field={job.jobName} /></Section>
    <Section title="Schedule"><Datum label="Due day" field={job.dueDay} /><Datum label="Due date" field={job.dueDate} /><Datum label="Due time" field={job.dueTime} /><Datum label="Priority" field={job.priority} /></Section>
    <Section title="Production"><Datum label="Raw recorded status" field={job.status} /><Datum label="Exposed" field={job.exposed} />{Object.entries(job.metrics).map(([name, metric]) => <Datum key={name} label={name.replaceAll("_", " ")} field={metric} />)}</Section>
    <Section title="Buyout"><Datum label="Ordered" field={job.buyoutOrdered} /><Datum label="Vendor & PO source (composite)" field={job.vendorPoComposite} /><Datum label="Received" field={job.buyoutReceived} /></Section>
    <Section title="Delivery"><Datum label="Delivery / Will Call" field={job.deliveryMode} /><Datum label="Day / date" field={job.deliveryDayDate} /><Datum label="Time" field={job.deliveryTime} /><Datum label="Contact" field={job.deliveryContact} /><Datum label="Phone" field={job.phone} /><Datum label="Text source field" field={job.textFlag} /></Section>
    <section className="detail-section"><h3>Office events <span className="prop-label">Independent evidence · no required sequence</span></h3><div className="event-line">{Object.entries(job.officeEvents).map(([name, field]) => <div className="event-card" key={name}><span>{name}</span><strong><Value field={field} /></strong></div>)}</div></section>
    <Section title="Notes"><Datum label="Operational note" field={job.operationalNote} /><Datum label="Office-only note" field={job.officeOnlyNote} /><Datum label="Entered by" field={job.enteredBy} /></Section>
    <section className="detail-section"><h3>Systems Awareness <span className="prop-label">PROP · review mode</span></h3>{job.findings.length ? <div className="finding-list">{job.findings.map((finding) => <article key={finding.evaluationId}><b>{finding.ruleId} · {finding.ruleVersion}</b><p>{finding.reason}</p><small>{finding.sourceCellIds.length} source inputs · proposed review only</small></article>)}</div> : <div className="empty-inline">No proposed review-mode findings for this record. Blocked rules remain excluded.</div>}</section>
    <section className="detail-section provenance-summary"><h3>Provenance</h3><p>{job.provenance.sourceFile} → {job.provenance.sheetName} → row {job.provenance.rowNumber}</p><code>{job.provenance.sourceHash.slice(0, 16)}… · {job.provenance.importBatchId}</code><button onClick={onSource}>Inspect mapped source cells</button></section>
  </div>;
}

function SourceDrawer({ job, close }: { job: OperationsPresentationDto; close: () => void }) { return <div className="drawer-backdrop" onMouseDown={close}><aside className="quick-drawer source-drawer" role="dialog" aria-modal="true" aria-label="Provenance and source cells" onMouseDown={(event) => event.stopPropagation()}><button className="close" onClick={close} aria-label="Close provenance">×</button><span className="eyebrow">IMMUTABLE SOURCE EVIDENCE</span><h2>{job.provenance.sheetName} · row {job.provenance.rowNumber}</h2><p>{job.provenance.sourceFile}</p><div className="source-list">{job.provenance.fields.map((field) => <article key={field.address}><div><b>{field.canonicalField}</b><code>{field.address}</code></div><small>{field.header ?? "No header"} · {field.excelType} · {field.presence}</small><p>{field.rawDisplay ?? labels[field.presence] ?? "No source display"}</p>{field.formulaText && <code>{field.formulaText}</code>}</article>)}</div></aside></div>; }

function JobTable({ jobs, open, source }: { jobs: readonly OperationsPresentationDto[]; open: (job: OperationsPresentationDto) => void; source: (job: OperationsPresentationDto) => void }) { return <div className="table-frame" role="region" aria-label="Jobs and releases table" tabIndex={0}><table><thead><tr><th>Attention</th><th>Legacy Job #</th><th>Customer</th><th>PO</th><th>Job Name / Release</th><th>Due</th><th>Priority</th><th>Status</th><th>Buyout</th><th>Delivery</th><th>Coil LBS</th><th>Optimized LBS</th><th>Source</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.jobReleaseId} tabIndex={0} onDoubleClick={() => open(job)} onKeyDown={(event) => { if (event.key === "Enter") open(job); if (event.key.toLowerCase() === "r") source(job); }}><td>{job.findings.length ? <span className="attention">{job.findings.length} PROP</span> : <span className="quiet">—</span>}</td><td><button className="record-link" onClick={() => open(job)}><Value field={job.legacyJobNumber} /></button></td><td><Value field={job.customer} /></td><td><Value field={job.po} /></td><td><Value field={job.jobName} /></td><td><Value field={job.dueDate} /></td><td><Value field={job.priority} /></td><td><span className="status-chip"><Value field={job.status} /></span></td><td><Value field={job.buyoutOrdered} /></td><td><Value field={job.deliveryMode} /></td><td className="metric"><Value field={job.metrics.coil_lbs!} /></td><td className="metric"><Value field={job.metrics.optimized_lbs!} /></td><td><button className="source-button" onClick={() => source(job)}>{job.provenance.sheetName} · {job.provenance.rowNumber}</button></td></tr>)}</tbody></table>{jobs.length === 0 && <div className="loading-grid">No records match the current filters.</div>}</div>; }

export function App() {
  const mode = new URLSearchParams(location.search).get("mode") === "masked" ? "masked" : "internal";
  const [path, setPath] = useState(location.pathname); const [data, setData] = useState<OperationsApiResponse | null>(null); const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState(new URLSearchParams(location.search).get("search") ?? ""); const [status, setStatus] = useState(new URLSearchParams(location.search).get("status") ?? "ALL"); const [era, setEra] = useState(new URLSearchParams(location.search).get("era") ?? "ALL"); const [rule, setRule] = useState(new URLSearchParams(location.search).get("rule") ?? "ALL"); const [sourceJob, setSourceJob] = useState<OperationsPresentationDto | null>(null);
  const searchRef = useRef<HTMLInputElement>(null); const filterRef = useRef<HTMLSelectElement>(null);
  useEffect(() => { fetch(`/api/operations?mode=${mode}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json() as OperationsApiResponse & { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Local source service unavailable"); setData(payload); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Local source service unavailable")); }, [mode]);
  useEffect(() => { const pop = () => setPath(location.pathname); addEventListener("popstate", pop); return () => removeEventListener("popstate", pop); }, []);
  useEffect(() => { const keys = (event: KeyboardEvent) => { if (event.key === "/" && document.activeElement?.tagName !== "INPUT") { event.preventDefault(); searchRef.current?.focus(); } if (event.key.toLowerCase() === "f" && !["INPUT", "SELECT", "TEXTAREA"].includes(document.activeElement?.tagName ?? "")) filterRef.current?.focus(); if (event.key === "Escape") setSourceJob(null); }; addEventListener("keydown", keys); return () => removeEventListener("keydown", keys); }, []);
  useEffect(() => { const url = new URL(location.href); for (const [key, value] of Object.entries({ search, status, era, rule })) value === "" || value === "ALL" ? url.searchParams.delete(key) : url.searchParams.set(key, value); url.searchParams.set("mode", mode); history.replaceState({}, "", url); }, [search, status, era, rule, mode]);
  const navigate = (nextPath: string, params: Record<string, string> = {}) => { const url = new URL(nextPath, location.origin); url.searchParams.set("mode", mode); for (const [key, value] of Object.entries(params)) if (value !== "ALL" && value !== "") url.searchParams.set(key, value); history.pushState({}, "", url); setPath(url.pathname); };
  const switchMode = () => { if (mode === "internal" && !confirm("Use masked presentation for this session?")) return; const next = new URL(location.href); next.searchParams.set("mode", mode === "internal" ? "masked" : "internal"); location.assign(next); };
  const jobs = useMemo(() => (data?.jobs ?? []).filter((job) => { const needle = search.trim().toLocaleLowerCase(); const text = [job.customer.display, job.po.display, job.jobName.display, job.legacyJobNumber.display, job.deliveryContact.display].join(" ").toLocaleLowerCase(); return (!needle || text.includes(needle)) && (status === "ALL" || job.status.display === status) && (era === "ALL" || job.provenance.sheetName.includes(era)); }), [data, search, status, era]);
  const detailId = path.startsWith("/operations/jobs/") ? decodeURIComponent(path.slice("/operations/jobs/".length)) : null; const detailJob = detailId ? data?.jobs.find((job) => job.jobReleaseId === detailId) ?? null : null;
  const active = path.includes("awareness") ? "awareness" : path.includes("history") ? "history" : path.includes("overview") || path === "/" ? "overview" : path.includes("estimating") ? "estimating" : "jobs";
  const findings = (data?.jobs ?? []).flatMap((job) => job.findings.map((finding) => ({ job, finding }))).filter(({ finding }) => rule === "ALL" || finding.ruleId === rule); const statuses = data ? Object.keys(data.summary.statusDistribution).sort() : [];
  return <div className="app-shell"><aside className="nav-rail"><div className="brand"><span className="brand-mark">T</span><div><strong>TITAN</strong><small>OPERATIONS · RC0</small></div></div><nav aria-label="Primary navigation"><a className={active === "overview" ? "active" : ""} onClick={(event) => { event.preventDefault(); navigate("/operations/overview"); }} href="/operations/overview">Overview</a><a className={active === "jobs" ? "active" : ""} onClick={(event) => { event.preventDefault(); navigate("/operations/jobs"); }} href="/operations/jobs">Jobs / Releases</a><a className={active === "awareness" ? "active" : ""} onClick={(event) => { event.preventDefault(); navigate("/operations/awareness"); }} href="/operations/awareness">Systems Awareness</a><a className={active === "history" ? "active" : ""} onClick={(event) => { event.preventDefault(); navigate("/operations/history"); }} href="/operations/history">Historical Explorer</a><hr /><a className={active === "estimating" ? "active" : ""} onClick={(event) => { event.preventDefault(); navigate("/estimating"); }} href="/estimating">Estimating <small>Sibling</small></a></nav><div className="boundary-note"><strong>Read-only source</strong><span>No workbook writeback</span></div></aside><main>{mode === "masked" && <div className="masked-banner">MASKED DEMO — NOT SOURCE DATA</div>}<header className="topbar"><div><span className="eyebrow">2025 WORK LEDGER</span><strong>{data ? `${data.snapshot.jobCount.toLocaleString()} qualified records · ${data.snapshot.reviewCount} review rows` : "Loading immutable snapshot…"}</strong></div><div className="topbar-meta"><span>{data?.snapshot.snapshotId ?? "Snapshot pending"}</span><button className="mode-switch" onClick={switchMode}>{mode === "internal" ? "Internal Data" : "Masked Demo"}<b>↔</b></button></div></header>
    {error && <div className="error-panel"><strong>Source unavailable</strong><span>{error}</span></div>}{!error && !data && <div className="loading-grid">Registering and importing the authorized workbook through the read-only source boundary…</div>}
    {data && detailJob && <JobDetail job={detailJob} onBack={() => navigate("/operations/jobs", { search, status, era })} onSource={() => setSourceJob(detailJob)} />}
    {data && !detailJob && active === "jobs" && <><header className="page-head"><div><span className="eyebrow">SOURCE-AWARE RECORDS</span><h1>Jobs / Releases</h1><p>One qualified workbook row per record. Unknowns stay visible.</p></div><div className="source-stamp"><span>SOURCE INTEGRITY</span><strong>Verified unchanged</strong><small>{data.snapshot.fileName}</small></div></header><section className="filter-bar"><label><span>Search records · /</span><input ref={searchRef} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Customer, PO, job, release…" /></label><label><span>Raw status · f</span><select ref={filterRef} value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><div className="filter-result"><strong>{jobs.length.toLocaleString()}</strong><span>qualified matches</span></div></section><JobTable jobs={jobs.slice(0, 500)} open={(job) => navigate(`/operations/jobs/${encodeURIComponent(job.jobReleaseId)}`, { search, status, era })} source={setSourceJob} /></>}
    {data && active === "overview" && <div className="content-page"><header className="page-head"><div><span className="eyebrow">SOURCE-QUALIFIED SYNTHESIS</span><h1>Operations Overview</h1><p>Navigation over qualified records—not an official KPI engine.</p></div></header><section className="snapshot-panel"><div><span>Active source</span><strong>{data.snapshot.fileName}</strong><small>{data.snapshot.sourceHash.slice(0, 20)}…</small></div><div><span>Qualified jobs / releases</span><strong>{data.snapshot.jobCount.toLocaleString()}</strong><small>Deterministic row contract v0.1</small></div><div><span>Review ledger</span><strong>{data.snapshot.reviewCount}</strong><small>Never silently promoted</small></div></section><h2 className="section-title">Proposed review attention</h2><section className="overview-grid">{["OPS-AWR-002", "OPS-AWR-003", "OPS-AWR-004", "OPS-AWR-007"].map((id) => <button key={id} onClick={() => navigate("/operations/awareness", { rule: id })}><span>{id} · PROP</span><strong>{data.summary.findingsByRule[id] ?? 0}</strong><small>Review-mode findings</small></button>)}</section><h2 className="section-title">Raw production status distribution</h2><section className="distribution">{Object.entries(data.summary.statusDistribution).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([name, count]) => <button key={name} onClick={() => navigate("/operations/jobs", { status: name })}><span>{name}</span><b>{count}</b></button>)}</section><div className="unavailable-callout"><b>Overdue / official annual totals unavailable</b><span>Blocked status/EOD semantics and unreconciled source-summary inclusion policy. No value is shown as zero.</span></div></div>}
    {data && active === "awareness" && <div className="content-page"><header className="page-head"><div><span className="eyebrow">DETERMINISTIC · INSPECTABLE · NON-MUTATING</span><h1>Systems Awareness</h1><p>Only proposed review-mode rules generate findings. Blocked definitions remain browsable and excluded.</p></div></header><section className="filter-bar"><label><span>Rule</span><select value={rule} onChange={(event) => setRule(event.target.value)}><option value="ALL">All proposed findings</option>{data.rules.map((item) => <option key={item.ruleId}>{item.ruleId}</option>)}</select></label><div className="filter-result"><strong>{findings.length}</strong><span>PROP findings</span></div></section><div className="awareness-layout"><section className="finding-table">{findings.slice(0, 500).map(({ job, finding }) => <article key={finding.evaluationId}><span className="prop-label">PROP · REVIEW</span><button onClick={() => navigate(`/operations/jobs/${encodeURIComponent(job.jobReleaseId)}`)}><Value field={job.jobName} /></button><b>{finding.ruleId} · {finding.ruleVersion}</b><p>{finding.reason}</p><small>{job.provenance.sheetName} row {job.provenance.rowNumber} · {finding.sourceCellIds.length} inputs</small></article>)}</section><aside className="rule-catalog"><h3>Rule catalog</h3>{data.rules.map((item) => <div key={item.ruleId}><b>{item.ruleId}</b><span>{item.disposition === "BLOCKED" ? "BLOCKED" : "PROP / REVIEW MODE"}</span><small>{item.title}</small></div>)}</aside></div></div>}
    {data && active === "history" && <div className="content-page"><header className="page-head"><div><span className="eyebrow">AUTHORIZED WORKBOOK EVIDENCE</span><h1>Historical Explorer</h1><p>Compare periods without erasing schema-era missingness.</p></div></header><section className="filter-bar"><label><span>Source month</span><select value={era} onChange={(event) => setEra(event.target.value)}><option value="ALL">All 2025 months</option>{["Jan", "Feb", "March", "April", "May", "June", "July", "Aug", "Sept", "Oct", "Nov", "Dec"].map((item) => <option key={item}>{item}</option>)}</select></label><div className="filter-result"><strong>{jobs.length.toLocaleString()}</strong><span>source records</span></div></section><div className="history-note"><b>Presence states remain literal</b><span>“Not collected in this period” is distinct from “Blank in source,” NA, annotations, malformed values, and numeric 0.</span></div><JobTable jobs={jobs.slice(0, 300)} open={(job) => navigate(`/operations/jobs/${encodeURIComponent(job.jobReleaseId)}`, { era })} source={setSourceJob} /></div>}
    {data && active === "estimating" && <div className="content-page sibling-page"><span className="eyebrow">ISOLATED SIBLING ROUTE</span><h1>Estimating</h1><p>Estimating is intentionally separated from Titan Operations RC0. No Operations state, Quote semantics, pricing logic, or quote-to-job automation crosses this boundary.</p><button onClick={() => navigate("/operations/overview")}>Return to Operations Overview</button></div>}
    {sourceJob && <SourceDrawer job={sourceJob} close={() => setSourceJob(null)} />}</main></div>;
}

const rootElement = document.getElementById("root");
if (rootElement) createRoot(rootElement).render(<StrictMode><App /></StrictMode>);
